# Generated by Django 4.1.5 on 2023-01-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalise',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_management.tag'),
        ),
    ]
